export type Platform = {
  id: number;
  name: string;
  db: string;
};

export const platforms: Platform[] = [
  { id: 1, name: 'Amiga', db: 'amiga.db' },
  { id: 3, name: 'Game Boy', db: 'game-boy.db' },
  { id: 4, name: 'Game Boy Advance', db: 'game-boy-advance.db' },
  { id: 5, name: 'Game Gear', db: 'game-gear.db' },
  { id: 6, name: 'Genesis', db: 'genesis.db' },
  { id: 7, name: 'Atari Lynx', db: 'atari-lynx.db' },
  { id: 8, name: 'Sega Master System', db: 'sega-master-system.db' },
  { id: 9, name: 'Super Nintendo Entertainment System', db: 'snes.db' },
  { id: 11, name: 'Amstrad CPC', db: 'amstrad-cpc.db' },
  { id: 12, name: 'Apple II', db: 'apple-ii.db' },
  { id: 13, name: 'Atari ST', db: 'atari-st.db' },
  { id: 14, name: 'Commodore 64', db: 'commodore-64.db' },
  { id: 15, name: 'MSX', db: 'msx.db' },
  { id: 16, name: 'ZX Spectrum', db: 'zx-spectrum.db' },
  { id: 17, name: 'Mac', db: 'mac.db' },
  { id: 18, name: 'PlayStation Portable', db: 'psp.db' },
  { id: 19, name: 'PlayStation 2', db: 'ps2.db' },
  { id: 20, name: 'Xbox 360', db: 'xb360.db' },
  { id: 21, name: 'Nintendo Entertainment System', db: 'nes.db' },
  { id: 22, name: 'PlayStation', db: 'psx.db' },
  { id: 23, name: 'GameCube', db: 'gamecube.db' },
  { id: 24, name: 'Atari 8-bit', db: 'atari-8-bit.db' },
  { id: 25, name: 'Neo Geo', db: 'neo-geo.db' },
  { id: 26, name: '3DO', db: '3d0.db' },
  { id: 27, name: 'CD-i', db: 'cd-i.db' },
  { id: 28, name: 'Jaguar', db: 'jaguar.db' },
  { id: 29, name: 'Sega CD', db: 'sega-cd.db' },
  { id: 30, name: 'VIC-20', db: 'vic-20.db' },
  { id: 31, name: 'Sega 32X', db: 'sega-32x.db' },
  { id: 32, name: 'Xbox', db: 'xbox.db' },
  { id: 34, name: 'N-Gage', db: 'n-gage.db' },
  { id: 35, name: 'PlayStation 3', db: 'ps3.db' },
  { id: 36, name: 'Wii', db: 'wii.db' },
  { id: 37, name: 'Dreamcast', db: 'dreamcase.db' },
  { id: 38, name: 'Apple IIgs', db: 'apple-iigs.db' },
  { id: 39, name: 'Amiga CD32', db: 'amiga-cd32.db' },
  { id: 40, name: 'Atari 2600', db: 'atari-2600.db' },
  { id: 42, name: 'Saturn', db: 'saturn.db' },
  { id: 43, name: 'Nintendo 64', db: 'n64.db' },
  { id: 47, name: 'ColecoVision', db: 'colecovision.db' },
  { id: 48, name: 'TI-99/4A', db: 'ti-99-4a.db' },
  { id: 51, name: 'Intellivision', db: 'intellivision.db' },
  { id: 52, name: 'Nintendo DS', db: 'nintendo-ds.db' },
  { id: 53, name: 'TurboGrafx-CD', db: 'turbografx-cd.db' },
  { id: 54, name: 'WonderSwan Color', db: 'wonderswan-color.db' },
  { id: 55, name: 'TurboGrafx-16', db: 'turbografx-16.db' },
  { id: 57, name: 'Game Boy Color', db: 'gbc.db' },
  { id: 58, name: 'Commodore 128', db: 'commodore-128.db' },
  { id: 59, name: 'Neo Geo CD', db: 'neo-geo-cd.db' },
  { id: 60, name: 'Odyssey 2', db: 'odyssey-2.db' },
  { id: 61, name: 'Dragon 32/64', db: 'dragon-32-64.db' },
  { id: 62, name: 'Commodore PET/CBM', db: 'commodore-pet-cbm.db' },
  { id: 63, name: 'TRS-80', db: 'trs-80.db' },
  { id: 64, name: 'Zodiac', db: 'zodiac.db' },
  { id: 65, name: 'WonderSwan', db: 'wonderswan.db' },
  { id: 66, name: 'Channel F', db: 'channel-f.db' },
  { id: 67, name: 'Atari 5200', db: 'atari-5200.db' },
  { id: 68, name: 'TRS-80 CoCo', db: 'trs-80-coco.db' },
  { id: 70, name: 'Atari 7800', db: 'atari-7800.db' },
  { id: 72, name: 'iPod', db: 'ipod.db' },
  { id: 74, name: 'Odyssey', db: 'odyssey.db' },
  { id: 75, name: 'PC-FX', db: 'pc-fx.db' },
  { id: 76, name: 'Vectrex', db: 'vectrex.db' },
  { id: 77, name: 'Game.Com', db: 'game-com.db' },
  { id: 78, name: 'Gizmondo', db: 'gizmondo.db' },
  { id: 79, name: 'Virtual Boy', db: 'virtual-boy.db' },
  { id: 80, name: 'Neo Geo Pocket', db: 'neo-geo-pocket.db' },
  { id: 81, name: 'Neo Geo Pocket Color', db: 'neo-geo-pocket-color.db' },
  { id: 82, name: 'V.Smile', db: 'v-smile.db' },
  { id: 83, name: 'Pinball', db: 'pinball.db' },
  { id: 84, name: 'Arcade', db: 'arcade.db' },
  { id: 85, name: 'NUON', db: 'nuon.db' },
  { id: 86, name: 'Xbox 360 Games Store', db: 'xbox-360-games-store.db' },
  { id: 87, name: 'Wii Shop', db: 'wii-show.db' },
  { id: 88, name: 'PlayStation Network (PS3)', db: 'psn-ps3.db' },
  { id: 89, name: 'Leapster', db: 'leapster.db' },
  { id: 90, name: 'Microvision', db: 'microvision.db' },
  { id: 91, name: 'Famicom Disk System', db: 'famicom-disk-system.db' },
  { id: 92, name: 'Pioneer LaserActive', db: 'pioneer-laseractive.db' },
  { id: 93, name: 'Adventure Vision', db: 'adventure-vision.db' },
  { id: 94, name: 'PC', db: 'pc.db' },
  { id: 95, name: 'Sharp X68000', db: 'sharp-x68000.db' },
  { id: 96, name: 'iPhone', db: 'iphone.db' },
  { id: 98, name: 'Satellaview', db: 'satellaview.db' },
  { id: 99, name: 'Arcadia 2001', db: 'arcadia-2001.db' },
  { id: 100, name: 'Aquarius', db: 'aquarius.db' },
  { id: 101, name: 'Nintendo 64DD', db: 'nintendo-64dd.db' },
  { id: 102, name: 'Pippin', db: 'pippin.db' },
  { id: 103, name: 'R-Zone', db: 'r-zone.db' },
  { id: 104, name: 'HyperScan', db: 'hyperscan.db' },
  { id: 105, name: 'Game Wave', db: 'game-wave.db' },
  { id: 106, name: 'DSiWare', db: 'dsiware.db' },
  { id: 107, name: 'RDI Halcyon', db: 'rdi-halcyon.db' },
  { id: 108, name: 'FM Towns', db: 'fm-towns.db' },
  { id: 109, name: 'NEC PC-8801', db: 'nec-pc-8801.db' },
  { id: 110, name: 'BBC Micro', db: 'bbc-micro.db' },
  { id: 111, name: 'PLATO', db: 'plato.db' },
  { id: 112, name: 'NEC PC-9801', db: 'nec-pc-9801.db' },
  { id: 113, name: 'Sharp X1', db: 'sharp-x1.db' },
  { id: 114, name: 'FM-7', db: 'fm-7.db' },
];
